@URL = http://localhost:4000
@TYPE = /api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTg4MjIwMzUsImV4cCI6MTU5ODgyNTYzNX0.geBrmZ7M65RhyXtiSciGArZn6UY2qOF-MC0XRNMC7w4

###
POST {{URL}}{{TYPE}}/customerLogin
Content-Type: application/json

{
    "email":"customer@boiler.com",
    "password":"qwe$7500"
}

### 
POST {{URL}}{{TYPE}}/addCustomer
Content-Type: application/json
Authorization: {{token}}

{
    "name":"dinesh",
    "lastName":"dfd",
    "address":"B12 last streen",
    "email":"c@boiler.com",
    "phone":9042141018,
    "panNo":"B1243234",
    "pinNo":"6777",
}

###
DELETE {{URL}}{{TYPE}}/deleteCustomerById/5f3d228d25c9297349aa9003
Content-Type: application/json
Authorization: {{token}}

###
GET  {{URL}}{{TYPE}}/getCustomer
Content-Type: application/json
Authorization: {{token}}

### 
POST {{URL}}{{TYPE}}/updateCustomerById
Content-Type: application/json
Authorization: {{token}}

{     
     "_id":"5f4a89c6419015149ded70f7",
    "name":"customer",
    "lastName":"kayal",
    "address":"B12 last streen",
    "email":"customer@boiler.com",
    "phoneNo":9042141018,
    "panNo":"B1243234",
    "pinNo":"6777",
}

###

GET  {{URL}}{{TYPE}}/getbyIDCustomer/{"_id":"5f3d228d25c9297349aa9003"}
Content-Type: application/json
Authorization: {{token}}
