@URL = http://localhost:4000
@TYPE = /api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTg4MTk2ODEsImV4cCI6MTU5ODgyMzI4MX0.d4p4LF5CXWpUIau9kVEoGYoO1hAcLOaq52RqJfSVYgA


###
POST {{URL}}{{TYPE}}/employeeLogin
Content-Type: application/json

{
    "email":"employee@boiler.com",
    "password":"qwe$7500"
}

### 
POST {{URL}}{{TYPE}}/addEmployee
Content-Type: application/json
Authorization: {{token}}

{
    "empId":"Id",
     "name":"employee",
     "lastName":"lastname",
    "address":"B12 last streen",
    "panNo":"B12 Street",
    "email":"employee@boiler.com",
    "password":"qwe$7500",
    "confirmPassword":"qwe$7500",
    "mobileNo":9042141018,
    "dob":"02-03-2020",
    "designation":"desig",
    "companyName":"company",
    "pinNo":"pinno",
}

###
DELETE {{URL}}{{TYPE}}/deleteEmployeeById/5f3d1aa2491708625039f065
Content-Type: application/json
Authorization: {{token}}

###
GET  {{URL}}{{TYPE}}/getEmployee
Content-Type: application/json
Authorization: {{token}}

### 
POST {{URL}}{{TYPE}}/updateEmployeeById
Content-Type: application/json
Authorization: {{token}}
{

    "_id":"5f492610bee1b569812648f2",
    "empId":"Id",
     "name":"employee",
     "lastName":"lastname",
    "address":"B12 last streen",
    "panNo":"B12 Street",
    "email":"employee@boiler.com",
    "password":"qwe$7500",
    "confirmPassword":"qwe$7500",
    "mobileNo":9042141018,
    "dob":"02-03-2020",
    "designation":"desig",
    "companyName":"company",
    "pinNo":"pinno",
}