@URL = http://localhost:4000
@TYPE = /api
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTg1OTE1MjIsImV4cCI6MTU5ODU5NTEyMn0.6esoXW4UiaA7X66wv__TUQk4WyK1a2VUEe7MkHDrrcc
###
POST {{URL}}{{TYPE}}/supplierLogin
Content-Type: application/json

{
    "email":"supplier@boiler.com",
    "password":"qwe$7500"
}

### 
POST {{URL}}{{TYPE}}/addSupplier
Content-Type: application/json
Authorization: {{token}}

{
    "name":"supplier",
    "lastName":"dfd",
    "address":"B12 last streen",
    "gstin":"B1243234",
    "email":"supplier@boiler.com",
    "phone":9042141018,
    "panNo":"B1243234",
    "pinNo":"6777",
    "password":"rathyr",
    "confirmPassword":"rathyr"
}

###
DELETE {{URL}}{{TYPE}}/deleteSupplierById/5f3d21eb25c9297349aa9002
Content-Type: application/json
Authorization: {{token}}

###
GET  {{URL}}{{TYPE}}/getSupplier
Content-Type: application/json
Authorization: {{token}}

### 
POST {{URL}}{{TYPE}}/updateSupplierById
Content-Type: application/json
Authorization: {{token}}

{     
     "_id":"5f492610bee1b569812648f2",
    "name":"customer",
    "lastName":"dfd",
    "address":"B12 last streen",
    "email":"customer@boiler.com",
    "phone":9042141018,
    "panNo":"B1243234",
    "pinNo":"6777",
    "gstin":"44444",
     "password":"rathyr",
    "confirmPassword":"rathyr"
}